"use client";
import './globals.css'
import type { Metadata } from 'next'
import Providers, { theme } from '@/components/Providers'
import { CacheProvider } from '@chakra-ui/next-js'
import { ColorModeScript } from '@chakra-ui/react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <CacheProvider>
          <Providers>
            {children}
          </Providers>
        </CacheProvider>
      </body>
    </html>
  )
}


// Chakra with next link
{/* <Link href='/about' color='blue.400' _hover={{ color: 'blue.500' }}>
  About
</Link> */}


// Chakra with next font
{/* <style jsx global>
  {`
    :root {
      --font-rubik: ${rubik.style.fontFamily};
    }
  `}
</style> */}